// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portochat.proto

package com.lttldrgn.portochat.proto;

public final class Portochat {
  private Portochat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PortoChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:portochat.PortoChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.portochat.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>.portochat.Request request = 1;</code>
     */
    com.lttldrgn.portochat.proto.Portochat.Request getRequest();
    /**
     * <code>.portochat.Request request = 1;</code>
     */
    com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder getRequestOrBuilder();

    public com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.ApplicationMessageCase getApplicationMessageCase();
  }
  /**
   * Protobuf type {@code portochat.PortoChatMessage}
   */
  public  static final class PortoChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:portochat.PortoChatMessage)
      PortoChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PortoChatMessage.newBuilder() to construct.
    private PortoChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PortoChatMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PortoChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.lttldrgn.portochat.proto.Portochat.Request.Builder subBuilder = null;
              if (applicationMessageCase_ == 1) {
                subBuilder = ((com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_).toBuilder();
              }
              applicationMessage_ =
                  input.readMessage(com.lttldrgn.portochat.proto.Portochat.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_);
                applicationMessage_ = subBuilder.buildPartial();
              }
              applicationMessageCase_ = 1;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_PortoChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_PortoChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.class, com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.Builder.class);
    }

    private int applicationMessageCase_ = 0;
    private java.lang.Object applicationMessage_;
    public enum ApplicationMessageCase
        implements com.google.protobuf.Internal.EnumLite {
      REQUEST(1),
      APPLICATIONMESSAGE_NOT_SET(0);
      private final int value;
      private ApplicationMessageCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ApplicationMessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static ApplicationMessageCase forNumber(int value) {
        switch (value) {
          case 1: return REQUEST;
          case 0: return APPLICATIONMESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ApplicationMessageCase
    getApplicationMessageCase() {
      return ApplicationMessageCase.forNumber(
          applicationMessageCase_);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    /**
     * <code>.portochat.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return applicationMessageCase_ == 1;
    }
    /**
     * <code>.portochat.Request request = 1;</code>
     */
    public com.lttldrgn.portochat.proto.Portochat.Request getRequest() {
      if (applicationMessageCase_ == 1) {
         return (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_;
      }
      return com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
    }
    /**
     * <code>.portochat.Request request = 1;</code>
     */
    public com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder getRequestOrBuilder() {
      if (applicationMessageCase_ == 1) {
         return (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_;
      }
      return com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (applicationMessageCase_ == 1) {
        output.writeMessage(1, (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (applicationMessageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lttldrgn.portochat.proto.Portochat.PortoChatMessage)) {
        return super.equals(obj);
      }
      com.lttldrgn.portochat.proto.Portochat.PortoChatMessage other = (com.lttldrgn.portochat.proto.Portochat.PortoChatMessage) obj;

      boolean result = true;
      result = result && getApplicationMessageCase().equals(
          other.getApplicationMessageCase());
      if (!result) return false;
      switch (applicationMessageCase_) {
        case 1:
          result = result && getRequest()
              .equals(other.getRequest());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (applicationMessageCase_) {
        case 1:
          hash = (37 * hash) + REQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getRequest().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lttldrgn.portochat.proto.Portochat.PortoChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code portochat.PortoChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:portochat.PortoChatMessage)
        com.lttldrgn.portochat.proto.Portochat.PortoChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_PortoChatMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_PortoChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.class, com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.Builder.class);
      }

      // Construct using com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        applicationMessageCase_ = 0;
        applicationMessage_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_PortoChatMessage_descriptor;
      }

      @java.lang.Override
      public com.lttldrgn.portochat.proto.Portochat.PortoChatMessage getDefaultInstanceForType() {
        return com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.lttldrgn.portochat.proto.Portochat.PortoChatMessage build() {
        com.lttldrgn.portochat.proto.Portochat.PortoChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lttldrgn.portochat.proto.Portochat.PortoChatMessage buildPartial() {
        com.lttldrgn.portochat.proto.Portochat.PortoChatMessage result = new com.lttldrgn.portochat.proto.Portochat.PortoChatMessage(this);
        if (applicationMessageCase_ == 1) {
          if (requestBuilder_ == null) {
            result.applicationMessage_ = applicationMessage_;
          } else {
            result.applicationMessage_ = requestBuilder_.build();
          }
        }
        result.applicationMessageCase_ = applicationMessageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lttldrgn.portochat.proto.Portochat.PortoChatMessage) {
          return mergeFrom((com.lttldrgn.portochat.proto.Portochat.PortoChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lttldrgn.portochat.proto.Portochat.PortoChatMessage other) {
        if (other == com.lttldrgn.portochat.proto.Portochat.PortoChatMessage.getDefaultInstance()) return this;
        switch (other.getApplicationMessageCase()) {
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case APPLICATIONMESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lttldrgn.portochat.proto.Portochat.PortoChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lttldrgn.portochat.proto.Portochat.PortoChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int applicationMessageCase_ = 0;
      private java.lang.Object applicationMessage_;
      public ApplicationMessageCase
          getApplicationMessageCase() {
        return ApplicationMessageCase.forNumber(
            applicationMessageCase_);
      }

      public Builder clearApplicationMessage() {
        applicationMessageCase_ = 0;
        applicationMessage_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.lttldrgn.portochat.proto.Portochat.Request, com.lttldrgn.portochat.proto.Portochat.Request.Builder, com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder> requestBuilder_;
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return applicationMessageCase_ == 1;
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public com.lttldrgn.portochat.proto.Portochat.Request getRequest() {
        if (requestBuilder_ == null) {
          if (applicationMessageCase_ == 1) {
            return (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_;
          }
          return com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
        } else {
          if (applicationMessageCase_ == 1) {
            return requestBuilder_.getMessage();
          }
          return com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
        }
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public Builder setRequest(com.lttldrgn.portochat.proto.Portochat.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          applicationMessage_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        applicationMessageCase_ = 1;
        return this;
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public Builder setRequest(
          com.lttldrgn.portochat.proto.Portochat.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          applicationMessage_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        applicationMessageCase_ = 1;
        return this;
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public Builder mergeRequest(com.lttldrgn.portochat.proto.Portochat.Request value) {
        if (requestBuilder_ == null) {
          if (applicationMessageCase_ == 1 &&
              applicationMessage_ != com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance()) {
            applicationMessage_ = com.lttldrgn.portochat.proto.Portochat.Request.newBuilder((com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_)
                .mergeFrom(value).buildPartial();
          } else {
            applicationMessage_ = value;
          }
          onChanged();
        } else {
          if (applicationMessageCase_ == 1) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        applicationMessageCase_ = 1;
        return this;
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (applicationMessageCase_ == 1) {
            applicationMessageCase_ = 0;
            applicationMessage_ = null;
            onChanged();
          }
        } else {
          if (applicationMessageCase_ == 1) {
            applicationMessageCase_ = 0;
            applicationMessage_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public com.lttldrgn.portochat.proto.Portochat.Request.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      public com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder getRequestOrBuilder() {
        if ((applicationMessageCase_ == 1) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (applicationMessageCase_ == 1) {
            return (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_;
          }
          return com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
        }
      }
      /**
       * <code>.portochat.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lttldrgn.portochat.proto.Portochat.Request, com.lttldrgn.portochat.proto.Portochat.Request.Builder, com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(applicationMessageCase_ == 1)) {
            applicationMessage_ = com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lttldrgn.portochat.proto.Portochat.Request, com.lttldrgn.portochat.proto.Portochat.Request.Builder, com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder>(
                  (com.lttldrgn.portochat.proto.Portochat.Request) applicationMessage_,
                  getParentForChildren(),
                  isClean());
          applicationMessage_ = null;
        }
        applicationMessageCase_ = 1;
        onChanged();;
        return requestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:portochat.PortoChatMessage)
    }

    // @@protoc_insertion_point(class_scope:portochat.PortoChatMessage)
    private static final com.lttldrgn.portochat.proto.Portochat.PortoChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lttldrgn.portochat.proto.Portochat.PortoChatMessage();
    }

    public static com.lttldrgn.portochat.proto.Portochat.PortoChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PortoChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<PortoChatMessage>() {
      @java.lang.Override
      public PortoChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PortoChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PortoChatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PortoChatMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lttldrgn.portochat.proto.Portochat.PortoChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:portochat.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string requestId = 1;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>string requestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>.portochat.Request.RequestType requestType = 2;</code>
     */
    int getRequestTypeValue();
    /**
     * <code>.portochat.Request.RequestType requestType = 2;</code>
     */
    com.lttldrgn.portochat.proto.Portochat.Request.RequestType getRequestType();

    /**
     * <code>string requestData = 3;</code>
     */
    java.lang.String getRequestData();
    /**
     * <code>string requestData = 3;</code>
     */
    com.google.protobuf.ByteString
        getRequestDataBytes();
  }
  /**
   * Protobuf type {@code portochat.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:portochat.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      requestId_ = "";
      requestType_ = 0;
      requestData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              requestData_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lttldrgn.portochat.proto.Portochat.Request.class, com.lttldrgn.portochat.proto.Portochat.Request.Builder.class);
    }

    /**
     * Protobuf enum {@code portochat.Request.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ChannelList = 0;</code>
       */
      ChannelList(0),
      /**
       * <code>ChannelUserList = 1;</code>
       */
      ChannelUserList(1),
      /**
       * <code>SetUserName = 2;</code>
       */
      SetUserName(2),
      /**
       * <code>UserList = 3;</code>
       */
      UserList(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ChannelList = 0;</code>
       */
      public static final int ChannelList_VALUE = 0;
      /**
       * <code>ChannelUserList = 1;</code>
       */
      public static final int ChannelUserList_VALUE = 1;
      /**
       * <code>SetUserName = 2;</code>
       */
      public static final int SetUserName_VALUE = 2;
      /**
       * <code>UserList = 3;</code>
       */
      public static final int UserList_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return ChannelList;
          case 1: return ChannelUserList;
          case 2: return SetUserName;
          case 3: return UserList;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lttldrgn.portochat.proto.Portochat.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:portochat.Request.RequestType)
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestId_;
    /**
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 2;
    private int requestType_;
    /**
     * <code>.portochat.Request.RequestType requestType = 2;</code>
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.portochat.Request.RequestType requestType = 2;</code>
     */
    public com.lttldrgn.portochat.proto.Portochat.Request.RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      com.lttldrgn.portochat.proto.Portochat.Request.RequestType result = com.lttldrgn.portochat.proto.Portochat.Request.RequestType.valueOf(requestType_);
      return result == null ? com.lttldrgn.portochat.proto.Portochat.Request.RequestType.UNRECOGNIZED : result;
    }

    public static final int REQUESTDATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object requestData_;
    /**
     * <code>string requestData = 3;</code>
     */
    public java.lang.String getRequestData() {
      java.lang.Object ref = requestData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestData_ = s;
        return s;
      }
    }
    /**
     * <code>string requestData = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestDataBytes() {
      java.lang.Object ref = requestData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
      }
      if (requestType_ != com.lttldrgn.portochat.proto.Portochat.Request.RequestType.ChannelList.getNumber()) {
        output.writeEnum(2, requestType_);
      }
      if (!getRequestDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
      }
      if (requestType_ != com.lttldrgn.portochat.proto.Portochat.Request.RequestType.ChannelList.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestType_);
      }
      if (!getRequestDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lttldrgn.portochat.proto.Portochat.Request)) {
        return super.equals(obj);
      }
      com.lttldrgn.portochat.proto.Portochat.Request other = (com.lttldrgn.portochat.proto.Portochat.Request) obj;

      boolean result = true;
      result = result && getRequestId()
          .equals(other.getRequestId());
      result = result && requestType_ == other.requestType_;
      result = result && getRequestData()
          .equals(other.getRequestData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + REQUESTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRequestData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lttldrgn.portochat.proto.Portochat.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lttldrgn.portochat.proto.Portochat.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code portochat.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:portochat.Request)
        com.lttldrgn.portochat.proto.Portochat.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lttldrgn.portochat.proto.Portochat.Request.class, com.lttldrgn.portochat.proto.Portochat.Request.Builder.class);
      }

      // Construct using com.lttldrgn.portochat.proto.Portochat.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = "";

        requestType_ = 0;

        requestData_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lttldrgn.portochat.proto.Portochat.internal_static_portochat_Request_descriptor;
      }

      @java.lang.Override
      public com.lttldrgn.portochat.proto.Portochat.Request getDefaultInstanceForType() {
        return com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.lttldrgn.portochat.proto.Portochat.Request build() {
        com.lttldrgn.portochat.proto.Portochat.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.lttldrgn.portochat.proto.Portochat.Request buildPartial() {
        com.lttldrgn.portochat.proto.Portochat.Request result = new com.lttldrgn.portochat.proto.Portochat.Request(this);
        result.requestId_ = requestId_;
        result.requestType_ = requestType_;
        result.requestData_ = requestData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lttldrgn.portochat.proto.Portochat.Request) {
          return mergeFrom((com.lttldrgn.portochat.proto.Portochat.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lttldrgn.portochat.proto.Portochat.Request other) {
        if (other == com.lttldrgn.portochat.proto.Portochat.Request.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (!other.getRequestData().isEmpty()) {
          requestData_ = other.requestData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lttldrgn.portochat.proto.Portochat.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lttldrgn.portochat.proto.Portochat.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestId_ = "";
      /**
       * <code>string requestId = 1;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>string requestId = 1;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestId_ = value;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.portochat.Request.RequestType requestType = 2;</code>
       */
      public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.portochat.Request.RequestType requestType = 2;</code>
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.portochat.Request.RequestType requestType = 2;</code>
       */
      public com.lttldrgn.portochat.proto.Portochat.Request.RequestType getRequestType() {
        @SuppressWarnings("deprecation")
        com.lttldrgn.portochat.proto.Portochat.Request.RequestType result = com.lttldrgn.portochat.proto.Portochat.Request.RequestType.valueOf(requestType_);
        return result == null ? com.lttldrgn.portochat.proto.Portochat.Request.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.portochat.Request.RequestType requestType = 2;</code>
       */
      public Builder setRequestType(com.lttldrgn.portochat.proto.Portochat.Request.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.portochat.Request.RequestType requestType = 2;</code>
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object requestData_ = "";
      /**
       * <code>string requestData = 3;</code>
       */
      public java.lang.String getRequestData() {
        java.lang.Object ref = requestData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestData = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRequestDataBytes() {
        java.lang.Object ref = requestData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestData = 3;</code>
       */
      public Builder setRequestData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestData = 3;</code>
       */
      public Builder clearRequestData() {
        
        requestData_ = getDefaultInstance().getRequestData();
        onChanged();
        return this;
      }
      /**
       * <code>string requestData = 3;</code>
       */
      public Builder setRequestDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:portochat.Request)
    }

    // @@protoc_insertion_point(class_scope:portochat.Request)
    private static final com.lttldrgn.portochat.proto.Portochat.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lttldrgn.portochat.proto.Portochat.Request();
    }

    public static com.lttldrgn.portochat.proto.Portochat.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.lttldrgn.portochat.proto.Portochat.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_portochat_PortoChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_portochat_PortoChatMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_portochat_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_portochat_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017portochat.proto\022\tportochat\"O\n\020PortoCha" +
      "tMessage\022%\n\007request\030\001 \001(\0132\022.portochat.Re" +
      "questH\000B\024\n\022ApplicationMessage\"\272\001\n\007Reques" +
      "t\022\021\n\trequestId\030\001 \001(\t\0223\n\013requestType\030\002 \001(" +
      "\0162\036.portochat.Request.RequestType\022\023\n\013req" +
      "uestData\030\003 \001(\t\"R\n\013RequestType\022\017\n\013Channel" +
      "List\020\000\022\023\n\017ChannelUserList\020\001\022\017\n\013SetUserNa" +
      "me\020\002\022\014\n\010UserList\020\003B\036\n\034com.lttldrgn.porto" +
      "chat.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_portochat_PortoChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_portochat_PortoChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_portochat_PortoChatMessage_descriptor,
        new java.lang.String[] { "Request", "ApplicationMessage", });
    internal_static_portochat_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_portochat_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_portochat_Request_descriptor,
        new java.lang.String[] { "RequestId", "RequestType", "RequestData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
